spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        generate_statistics: true #JPA 쿼리 성능 통계
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #DB에 전달하는 SQL 형식 지정
    hibernate:
      ddl-auto: create

logging:
  level:
    site.shkrr: debug

test:
  card_num: ${test_card_num}
  card_year: ${test_card_year}
  card_month: ${test_card_month}
  card_customer_id: ${test_card_customer_id}
  card_password: ${test_card_password}