spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/local;MODE=MySQL;DATABASE_TO_LOWER=TRUE #mysql 모드 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #DB에 전달하는 SQL 형식 지정
    hibernate:
      ddl-auto: create