spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


sms:
  api_key: ${sms_api_key}
  secret_key: ${sms_secret_key}

jwt:
  secret_key: ${jwt_secret_key}